import type { VercelRequest, VercelResponse } from "@vercel/node";
import { isAuthenticated, getAuthTier } from "./_auth";

const challenges = [
  // === General Cybersecurity (Beginner, no AI) ===
  {
    id: "phishing",
    title: "Riconosci il Phishing",
    category: "Awareness",
    difficulty: "beginner",
    description: "Analizza email sospette e impara a distinguere i messaggi di phishing da quelli legittimi.",
    targetPath: "/vuln/phishing",
    type: "general",
  },
  {
    id: "sender",
    title: "Analizza il Mittente",
    category: "Awareness",
    difficulty: "beginner",
    description: "Impara a verificare l'autenticità dei mittenti email analizzando domini e indirizzi.",
    targetPath: "/vuln/sender",
    type: "general",
  },
  {
    id: "passwords",
    title: "Password Sicure",
    category: "Awareness",
    difficulty: "beginner",
    description: "Scopri cosa rende una password sicura e testa la forza delle tue password.",
    targetPath: "/vuln/passwords",
    type: "general",
  },
  {
    id: "suspicious-urls",
    title: "URL Sospetti",
    category: "Awareness",
    difficulty: "beginner",
    description: "Impara a riconoscere link pericolosi prima di cliccarci sopra.",
    targetPath: "/vuln/suspicious-urls",
    type: "general",
  },
  {
    id: "social-engineering",
    title: "Ingegneria Sociale",
    category: "Awareness",
    difficulty: "beginner",
    description: "Riconosci i tentativi di manipolazione e impara a difenderti dal social engineering.",
    targetPath: "/vuln/social-engineering",
    type: "general",
  },
  {
    id: "permissions",
    title: "Permessi App e Privacy",
    category: "Awareness",
    difficulty: "beginner",
    description: "Valuta quali permessi sono ragionevoli per un'app e quali sono sospetti.",
    targetPath: "/vuln/permissions",
    type: "general",
  },
  {
    id: "public-wifi",
    title: "Wi-Fi Pubblico",
    category: "Awareness",
    difficulty: "beginner",
    description: "Impara i rischi delle reti Wi-Fi pubbliche e come proteggerti.",
    targetPath: "/vuln/public-wifi",
    type: "general",
  },
  {
    id: "backup",
    title: "Aggiornamenti e Backup",
    category: "Awareness",
    difficulty: "beginner",
    description: "Conosci le buone pratiche per aggiornamenti, backup e protezione dai ransomware.",
    targetPath: "/vuln/backup",
    type: "general",
  },
  {
    id: "fake-notifications",
    title: "Notifiche Fasulle",
    category: "Awareness",
    difficulty: "beginner",
    description: "Impara a distinguere le notifiche del browser legittime da quelle fasulle usate per truffe e malware.",
    targetPath: "/vuln/fake-notifications",
    type: "general",
  },
  {
    id: "qr-codes",
    title: "Truffe con QR Code",
    category: "Awareness",
    difficulty: "beginner",
    description: "Impara a riconoscere QR Code truffa e a proteggerti dal quishing.",
    targetPath: "/vuln/qr-codes",
    type: "general",
  },
  // === Networking: LAN & Infrastructure ===
  {
    id: "net-devices",
    title: "Dispositivi di Rete",
    category: "LAN",
    difficulty: "beginner",
    description: "Riconosci hub, switch, router e access point e scegli il dispositivo giusto per ogni scenario.",
    targetPath: "/vuln/net-devices",
    type: "networking",
  },
  {
    id: "net-cabling",
    title: "Cablaggio Strutturato",
    category: "LAN",
    difficulty: "beginner",
    description: "Scegli il cavo di rete corretto in base a distanza, velocità e ambiente.",
    targetPath: "/vuln/net-cabling",
    type: "networking",
  },
  {
    id: "net-subnetting",
    title: "Subnetting IPv4",
    category: "LAN",
    difficulty: "beginner",
    description: "Calcola network address, broadcast, range host e subnet mask a partire da IP e CIDR.",
    targetPath: "/vuln/net-subnetting",
    type: "networking",
  },
  {
    id: "net-vlan",
    title: "VLAN e Segmentazione",
    category: "LAN",
    difficulty: "beginner",
    description: "Configura le VLAN assegnando porte a reti logiche separate su uno switch.",
    targetPath: "/vuln/net-vlan",
    type: "networking",
  },
  {
    id: "net-dhcp",
    title: "DHCP: il protocollo DORA",
    category: "LAN",
    difficulty: "beginner",
    description: "Comprendi il processo Discover-Offer-Request-Acknowledge e le opzioni DHCP.",
    targetPath: "/vuln/net-dhcp",
    type: "networking",
  },
  {
    id: "net-nat",
    title: "NAT e PAT",
    category: "LAN",
    difficulty: "beginner",
    description: "Comprendi come NAT e PAT traducono gli indirizzi IP interni verso l'esterno.",
    targetPath: "/vuln/net-nat",
    type: "networking",
  },
  // === Networking: DNS ===
  {
    id: "dns-resolution",
    title: "Risoluzione DNS",
    category: "DNS",
    difficulty: "beginner",
    description: "Segui passo passo una query DNS dalla richiesta alla risposta.",
    targetPath: "/vuln/dns-resolution",
    type: "dns",
  },
  {
    id: "dns-records",
    title: "Record DNS",
    category: "DNS",
    difficulty: "beginner",
    description: "Associa ogni tipo di record DNS (A, AAAA, CNAME, MX, TXT, SRV) al suo utilizzo.",
    targetPath: "/vuln/dns-records",
    type: "dns",
  },
  {
    id: "dns-dig",
    title: "Leggere un output dig",
    category: "DNS",
    difficulty: "beginner",
    description: "Interpreta l'output del comando dig identificando record, TTL e sezioni.",
    targetPath: "/vuln/dns-dig",
    type: "dns",
  },
  {
    id: "dns-email-auth",
    title: "SPF, DKIM e DMARC",
    category: "DNS",
    difficulty: "beginner",
    description: "Configura i record TXT per proteggere il dominio dallo spoofing email.",
    targetPath: "/vuln/dns-email-auth",
    type: "dns",
  },
  {
    id: "dns-attacks",
    title: "Attacchi DNS",
    category: "DNS",
    difficulty: "beginner",
    description: "Identifica gli attacchi DNS: cache poisoning, hijacking, typosquatting e tunneling.",
    targetPath: "/vuln/dns-attacks",
    type: "dns",
  },
  {
    id: "dns-troubleshooting",
    title: "Troubleshooting DNS",
    category: "DNS",
    difficulty: "beginner",
    description: "Risolvi problemi di rete seguendo un metodo diagnostico step-by-step.",
    targetPath: "/vuln/dns-troubleshooting",
    type: "dns",
  },
  // === Networking: TCP, UDP & Ports ===
  {
    id: "tcp-handshake",
    title: "Three-Way Handshake",
    category: "TCP/UDP",
    difficulty: "beginner",
    description: "Completa la sequenza SYN, SYN-ACK, ACK con i numeri di sequenza corretti.",
    targetPath: "/vuln/tcp-handshake",
    type: "tcp-udp",
  },
  {
    id: "tcp-vs-udp",
    title: "TCP vs UDP",
    category: "TCP/UDP",
    difficulty: "beginner",
    description: "Scegli il protocollo di trasporto corretto per ogni servizio e applicazione.",
    targetPath: "/vuln/tcp-vs-udp",
    type: "tcp-udp",
  },
  {
    id: "tcp-ports",
    title: "Porte di Rete",
    category: "TCP/UDP",
    difficulty: "beginner",
    description: "Associa i servizi alle porte well-known: SSH, HTTP, HTTPS, SMTP, RDP, SMB e altre.",
    targetPath: "/vuln/tcp-ports",
    type: "tcp-udp",
  },
  {
    id: "tcp-segment",
    title: "Anatomia del Segmento TCP",
    category: "TCP/UDP",
    difficulty: "beginner",
    description: "Analizza un header TCP campo per campo: flag, window size, sequence number.",
    targetPath: "/vuln/tcp-segment",
    type: "tcp-udp",
  },
  {
    id: "tcp-firewall",
    title: "Regole Firewall",
    category: "TCP/UDP",
    difficulty: "beginner",
    description: "Scrivi regole firewall per filtrare traffico in base a porta, protocollo e direzione.",
    targetPath: "/vuln/tcp-firewall",
    type: "tcp-udp",
  },
  {
    id: "tcp-netstat",
    title: "Analisi Connessioni (netstat)",
    category: "TCP/UDP",
    difficulty: "beginner",
    description: "Interpreta l'output di netstat/ss per identificare connessioni sospette.",
    targetPath: "/vuln/tcp-netstat",
    type: "tcp-udp",
  },
  // === Switch e LAN Avanzate ===
  {
    id: "sw-mac-table",
    title: "Switch e MAC Table",
    category: "Switch LAN",
    difficulty: "beginner",
    description: "Come funziona uno switch: MAC table, forwarding, flooding, domini di collisione e broadcast.",
    targetPath: "/vuln/sw-mac-table",
    type: "switch-lan",
  },
  {
    id: "sw-vlan-trunk",
    title: "VLAN e Trunk 802.1Q",
    category: "Switch LAN",
    difficulty: "beginner",
    description: "Segmentazione logica con VLAN, access e trunk port, tag 802.1Q, inter-VLAN routing.",
    targetPath: "/vuln/sw-vlan-trunk",
    type: "switch-lan",
  },
  {
    id: "sw-stp-lag",
    title: "STP e Ridondanza",
    category: "Switch LAN",
    difficulty: "beginner",
    description: "Spanning Tree Protocol, loop di rete, RSTP, EtherChannel e Link Aggregation.",
    targetPath: "/vuln/sw-stp-lag",
    type: "switch-lan",
  },
  {
    id: "sw-security",
    title: "Sicurezza Switch",
    category: "Switch LAN",
    difficulty: "beginner",
    description: "Port security, DHCP snooping, ARP inspection, QoS e gestione switch.",
    targetPath: "/vuln/sw-security",
    type: "switch-lan",
  },
  // === WiFi e Reti Wireless ===
  {
    id: "wifi-standards",
    title: "Standard 802.11",
    category: "WiFi",
    difficulty: "beginner",
    description: "Evoluzione WiFi da b/g/n/ac/ax, bande 2.4/5/6 GHz, canali, MIMO e OFDMA.",
    targetPath: "/vuln/wifi-standards",
    type: "wifi",
  },
  {
    id: "wifi-modes",
    title: "Modalita Operative WiFi",
    category: "WiFi",
    difficulty: "beginner",
    description: "AP, client, repeater, extender, WDS, bridge e mesh: quale scegliere e quando.",
    targetPath: "/vuln/wifi-modes",
    type: "wifi",
  },
  {
    id: "wifi-bridges",
    title: "Ponti Radio e Outdoor",
    category: "WiFi",
    difficulty: "beginner",
    description: "Link punto-punto, punto-multipunto, zona di Fresnel e progettazione outdoor.",
    targetPath: "/vuln/wifi-bridges",
    type: "wifi",
  },
  {
    id: "wifi-security",
    title: "Sicurezza WiFi",
    category: "WiFi",
    difficulty: "beginner",
    description: "Da WEP a WPA3, Personal vs Enterprise 802.1X, attacchi e contromisure.",
    targetPath: "/vuln/wifi-security",
    type: "wifi",
  },
  {
    id: "wifi-design",
    title: "Progettazione e Roaming",
    category: "WiFi",
    difficulty: "beginner",
    description: "Site survey, copertura, roaming 802.11r/k/v, controller WiFi e best practice.",
    targetPath: "/vuln/wifi-design",
    type: "wifi",
  },
  // === Intelligenza Artificiale ===
  {
    id: "ai-llm",
    title: "Cos'è un LLM",
    category: "AI",
    difficulty: "beginner",
    description: "Scopri come funzionano i Large Language Model: token, temperatura, hallucination e context window.",
    targetPath: "/vuln/ai-llm",
    type: "ai",
  },
  {
    id: "ai-prompt",
    title: "Prompt Engineering",
    category: "AI",
    difficulty: "beginner",
    description: "Impara le tecniche per comunicare efficacemente con l'AI: few-shot, chain-of-thought, role prompting.",
    targetPath: "/vuln/ai-prompt",
    type: "ai",
  },
  {
    id: "ai-models",
    title: "Modelli e Servizi AI",
    category: "AI",
    difficulty: "beginner",
    description: "GPT, Claude, Gemini, Llama: confronta modelli closed e open-source, SaaS e self-hosted.",
    targetPath: "/vuln/ai-models",
    type: "ai",
  },
  {
    id: "ai-deepfake",
    title: "Deepfake e Contenuti Generati",
    category: "AI",
    difficulty: "beginner",
    description: "Riconosci deepfake video, voice cloning e immagini generate. Impara a verificare l'autenticità.",
    targetPath: "/vuln/ai-deepfake",
    type: "ai",
  },
  {
    id: "ai-privacy",
    title: "AI e Privacy",
    category: "AI",
    difficulty: "beginner",
    description: "Shadow AI, GDPR, data leakage: gestisci i rischi privacy quando usi strumenti di intelligenza artificiale.",
    targetPath: "/vuln/ai-privacy",
    type: "ai",
  },
  {
    id: "ai-tools",
    title: "Strumenti AI nel Lavoro",
    category: "AI",
    difficulty: "beginner",
    description: "Usa l'AI come assistente: best practice per coding, documenti, analisi dati e i limiti da conoscere.",
    targetPath: "/vuln/ai-tools",
    type: "ai",
  },
  // === Technical Cybersecurity (with AI) ===
  {
    id: "xss",
    title: "Cross-Site Scripting (XSS)",
    category: "Injection",
    difficulty: "easy",
    description: "Inject JavaScript into a forum with reflected and stored XSS vulnerabilities.",
    targetPath: "/vuln/xss",
    type: "technical",
  },
  {
    id: "sqli",
    title: "SQL Injection",
    category: "Injection",
    difficulty: "medium",
    description: "Bypass authentication and extract data through SQL injection.",
    targetPath: "/vuln/sqli",
    type: "technical",
  },
  {
    id: "csrf",
    title: "Cross-Site Request Forgery (CSRF)",
    category: "Session",
    difficulty: "medium",
    description: "Forge cross-site requests to transfer funds without CSRF protection.",
    targetPath: "/vuln/csrf",
    type: "technical",
  },
  {
    id: "cmdi",
    title: "Command Injection",
    category: "Injection",
    difficulty: "hard",
    description: "Exploit a ping utility that passes user input directly to a shell command.",
    targetPath: "/vuln/cmdi",
    type: "technical",
  },
  {
    id: "idor",
    title: "Insecure Direct Object Reference (IDOR)",
    category: "Access Control",
    difficulty: "medium",
    description: "Access other users' profiles by manipulating predictable object identifiers.",
    targetPath: "/vuln/idor",
    type: "technical",
  },
  {
    id: "broken-auth",
    title: "Broken Authentication",
    category: "Session",
    difficulty: "hard",
    description: "Forge session tokens to impersonate the admin user.",
    targetPath: "/vuln/broken-auth",
    type: "technical",
  },
  {
    id: "path-traversal",
    title: "Path Traversal",
    category: "Access Control",
    difficulty: "hard",
    description: "Escape the file directory and read sensitive files from the server.",
    targetPath: "/vuln/path-traversal",
    type: "technical",
  },
];

export default function handler(req: VercelRequest, res: VercelResponse) {
  if (!isAuthenticated(req)) return res.status(401).json({ error: "Unauthorized" });

  const tier = getAuthTier(req);

  const { id } = req.query;
  if (id) {
    const challenge = challenges.find((c) => c.id === id);
    if (!challenge) return res.status(404).json({ error: "Not found" });
    return res.json(challenge);
  }

  const PROXIMA_TYPES = ["general", "networking", "dns"];
  const filtered = tier === "pro" ? challenges
    : tier === "proxima" ? challenges.filter(c => PROXIMA_TYPES.includes(c.type))
    : challenges.filter(c => c.type === "general");
  return res.json(filtered);
}
